"""Repository ports for Orion persistence."""

from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol

from musicclean.orion.domain import (
    Album,
    Artist,
    AudioFile,
    Disc,
    Edition,
    EvidenceRecord,
    Library,
    Recording,
    TrackAppearance,
)
from musicclean.orion.shared import EntityId


class LibraryRepository(Protocol):
    def get(self, library_id: EntityId) -> Library | None: ...
    def list_all(self) -> tuple[Library, ...]: ...
    def save(self, library: Library) -> None: ...


class ArtistRepository(Protocol):
    def get(self, artist_id: EntityId) -> Artist | None: ...
    def find_by_name(self, name: str) -> tuple[Artist, ...]: ...
    def save(self, artist: Artist) -> None: ...


class AlbumRepository(Protocol):
    def get(self, album_id: EntityId) -> Album | None: ...
    def find_by_title(self, title: str) -> tuple[Album, ...]: ...
    def save(self, album: Album) -> None: ...


class EditionRepository(Protocol):
    def get(self, edition_id: EntityId) -> Edition | None: ...
    def list_for_album(self, album_id: EntityId) -> tuple[Edition, ...]: ...
    def save(self, edition: Edition) -> None: ...


class DiscRepository(Protocol):
    def get(self, disc_id: EntityId) -> Disc | None: ...
    def list_for_edition(self, edition_id: EntityId) -> tuple[Disc, ...]: ...
    def save(self, disc: Disc) -> None: ...


class RecordingRepository(Protocol):
    def get(self, recording_id: EntityId) -> Recording | None: ...
    def find_by_title(self, title: str) -> tuple[Recording, ...]: ...
    def save(self, recording: Recording) -> None: ...


class TrackAppearanceRepository(Protocol):
    def get(self, track_appearance_id: EntityId) -> TrackAppearance | None: ...
    def list_for_disc(self, disc_id: EntityId) -> tuple[TrackAppearance, ...]: ...
    def list_for_recording(self, recording_id: EntityId) -> tuple[TrackAppearance, ...]: ...
    def save(self, track_appearance: TrackAppearance) -> None: ...


class AudioFileRepository(Protocol):
    def get(self, audio_file_id: EntityId) -> AudioFile | None: ...
    def get_by_location(self, location: str) -> AudioFile | None: ...
    def list_for_recording(self, recording_id: EntityId) -> tuple[AudioFile, ...]: ...
    def save(self, audio_file: AudioFile) -> None: ...
    def save_many(self, audio_files: Iterable[AudioFile]) -> None: ...


class EvidenceRepository(Protocol):
    """Append-oriented persistence contract for Evidence records."""

    def save(self, evidence: EvidenceRecord) -> None: ...
    def save_many(self, evidence: Iterable[EvidenceRecord]) -> None: ...
    def list_for_subject(self, subject_id: EntityId) -> tuple[EvidenceRecord, ...]: ...
