"""Repository ports for Orion persistence."""

from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol

from musicclean.orion.domain import (
    ActionPlan,
    Album,
    Artist,
    AudioFile,
    AuthorizationGrant,
    Decision,
    DecisionReview,
    Disc,
    Edition,
    EvidenceRecord,
    ExecutionKind,
    ExecutionRecord,
    KnowledgeFact,
    Library,
    ReconciliationFinding,
    Recording,
    TrackAppearance,
)
from musicclean.orion.shared import EntityId


class LibraryRepository(Protocol):
    def get(self, library_id: EntityId) -> Library | None: ...
    def list_all(self) -> tuple[Library, ...]: ...
    def save(self, library: Library) -> None: ...


class ArtistRepository(Protocol):
    def get(self, artist_id: EntityId) -> Artist | None: ...
    def find_by_name(self, name: str) -> tuple[Artist, ...]: ...
    def save(self, artist: Artist) -> None: ...


class AlbumRepository(Protocol):
    def get(self, album_id: EntityId) -> Album | None: ...
    def find_by_title(self, title: str) -> tuple[Album, ...]: ...
    def save(self, album: Album) -> None: ...


class EditionRepository(Protocol):
    def get(self, edition_id: EntityId) -> Edition | None: ...
    def list_for_album(self, album_id: EntityId) -> tuple[Edition, ...]: ...
    def save(self, edition: Edition) -> None: ...


class DiscRepository(Protocol):
    def get(self, disc_id: EntityId) -> Disc | None: ...
    def list_for_edition(self, edition_id: EntityId) -> tuple[Disc, ...]: ...
    def save(self, disc: Disc) -> None: ...


class RecordingRepository(Protocol):
    def get(self, recording_id: EntityId) -> Recording | None: ...
    def find_by_title(self, title: str) -> tuple[Recording, ...]: ...
    def save(self, recording: Recording) -> None: ...


class TrackAppearanceRepository(Protocol):
    def get(self, track_appearance_id: EntityId) -> TrackAppearance | None: ...
    def list_for_disc(self, disc_id: EntityId) -> tuple[TrackAppearance, ...]: ...
    def list_for_recording(self, recording_id: EntityId) -> tuple[TrackAppearance, ...]: ...
    def save(self, track_appearance: TrackAppearance) -> None: ...


class AudioFileRepository(Protocol):
    def get(self, audio_file_id: EntityId) -> AudioFile | None: ...
    def get_by_location(self, location: str) -> AudioFile | None: ...
    def list_for_recording(self, recording_id: EntityId) -> tuple[AudioFile, ...]: ...
    def save(self, audio_file: AudioFile) -> None: ...
    def save_many(self, audio_files: Iterable[AudioFile]) -> None: ...


class EvidenceRepository(Protocol):
    def save(self, evidence: EvidenceRecord) -> None: ...
    def save_many(self, evidence: Iterable[EvidenceRecord]) -> None: ...
    def list_for_subject(self, subject_id: EntityId) -> tuple[EvidenceRecord, ...]: ...


class KnowledgeRepository(Protocol):
    def save(self, fact: KnowledgeFact) -> None: ...
    def save_many(self, facts: Iterable[KnowledgeFact]) -> None: ...
    def list_for_subject(self, subject_id: EntityId) -> tuple[KnowledgeFact, ...]: ...


class DecisionRepository(Protocol):
    def get(self, decision_id: EntityId) -> Decision | None: ...
    def save(self, decision: Decision) -> None: ...
    def save_many(self, decisions: Iterable[Decision]) -> None: ...
    def list_for_subject(self, subject_id: EntityId) -> tuple[Decision, ...]: ...


class ReviewRepository(Protocol):
    def save(self, review: DecisionReview) -> None: ...
    def latest_for_decision(self, decision_id: EntityId) -> DecisionReview | None: ...


class AuthorizationRepository(Protocol):
    def get(self, authorization_id: EntityId) -> AuthorizationGrant | None: ...
    def save(self, grant: AuthorizationGrant) -> None: ...
    def latest_for_decision(
        self,
        decision_id: EntityId,
    ) -> AuthorizationGrant | None: ...


class ActionPlanRepository(Protocol):
    def save(self, plan: ActionPlan) -> None: ...
    def get(self, plan_id: EntityId) -> ActionPlan | None: ...
    def list_for_decision(self, decision_id: EntityId) -> tuple[ActionPlan, ...]: ...


class ExecutionRepository(Protocol):
    def save(self, execution: ExecutionRecord) -> None: ...
    def list_for_plan(self, plan_id: EntityId) -> tuple[ExecutionRecord, ...]: ...
    def latest_for_plan_kind(
        self,
        plan_id: EntityId,
        kind: ExecutionKind,
    ) -> ExecutionRecord | None: ...


class ReconciliationRepository(Protocol):
    """Append-only history of filesystem/database consistency checks."""

    def save(self, finding: ReconciliationFinding) -> None: ...
    def list_for_plan(self, plan_id: EntityId) -> tuple[ReconciliationFinding, ...]: ...
